"""Rename picture field to image

Revision ID: 23038ff1d3d7
Revises: cfeb710bcb7e
Create Date: 2025-11-18 14:51:30.426709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23038ff1d3d7'
down_revision: Union[str, Sequence[str], None] = 'cfeb710bcb7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('article', 'picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('article', 'image')
    # ### end Alembic commands ###
