"""Add tariff to user

Revision ID: cfeb710bcb7e
Revises: 27360866e5d8
Create Date: 2025-11-13 18:52:21.551922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfeb710bcb7e'
down_revision: Union[str, Sequence[str], None] = '27360866e5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tariff_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'tariff', ['tariff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'tariff_id')
    # ### end Alembic commands ###
